"""Add default timestamp value for added_date and edit_date

Revision ID: d86c5df442a6
Revises: df99fae8341a
Create Date: 2024-07-16 18:56:54.302457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86c5df442a6'
down_revision: Union[str, None] = 'df99fae8341a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'recipe',
        'added_date',
        existing_type=sa.DateTime(),
        server_default=sa.text("'1970-01-01 00:00:00'"),
        existing_nullable=False
    )
    
    # Ajoute la valeur par défaut à la colonne edit_date
    op.alter_column(
        'recipe',
        'edit_date',
        existing_type=sa.DateTime(),
        server_default=sa.text("'1970-01-01 00:00:00'"),
        existing_nullable=False
    )
    
    # Met à jour les enregistrements existants avec NULL pour added_date
    op.execute(
        """
        UPDATE "recipe"
        SET added_date = '1970-01-01 00:00:00'
        WHERE added_date IS NULL;
        """
    )
    
    # Met à jour les enregistrements existants avec NULL pour edit_date
    op.execute(
        """
        UPDATE "recipe"
        SET edit_date = '1970-01-01 00:00:00'
        WHERE edit_date IS NULL;
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'recipe',
        'added_date',
        server_default=None,
        existing_type=sa.DateTime(),
        existing_nullable=False
    )
    
    # Supprime la valeur par défaut de la colonne edit_date
    op.alter_column(
        'recipe',
        'edit_date',
        server_default=None,
        existing_type=sa.DateTime(),
        existing_nullable=False
    )
    # ### end Alembic commands ###
